export { default as AboutSection } from "./About"
export { default as ContactSection } from "./Contact"
export { default as SectionHeading } from "./Heading"
export { default as HeroSection } from "./Hero"
export { default as MiniAppsSection } from "./MiniApps"
export { default as ProjectsSection } from "./Projects"
export { default as SkillsSection } from "./Skills"
